/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package s4;

import java.awt.Color;

/**
 *
 * @author jlgallego99
 */
public class PanelBotones extends javax.swing.JPanel {

    /**
     * Creates new form PanelBotones
     */
    public PanelBotones() {
        BotonEncender.setForeground(Color.GREEN);
        BotonEncender.setText("ENCENDER");
        estado.setText("APAGADO");
        estado.setForeground(Color.RED);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        estado = new javax.swing.JLabel();
        BotonFrenar = new javax.swing.JButton();
        BotonEncender = new javax.swing.JToggleButton();
        BotonAcelerar = new javax.swing.JToggleButton();

        jLabel1.setText("Mandos");

        estado.setText("-");

        BotonFrenar.setText("FRENAR");
        BotonFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFrenarActionPerformed(evt);
            }
        });

        BotonEncender.setText("ENCENDER");
        BotonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEncenderActionPerformed(evt);
            }
        });

        BotonAcelerar.setText("ACELERAR");
        BotonAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAcelerarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(BotonEncender)
                .addGap(82, 82, 82)
                .addComponent(BotonAcelerar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addComponent(BotonFrenar)
                .addGap(14, 14, 14))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(estado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(4, 4, 4)
                .addComponent(estado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonFrenar)
                    .addComponent(BotonEncender)
                    .addComponent(BotonAcelerar))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFrenarActionPerformed
        // Frenando solo si el motor está encendido y el acelerador no está pulsado
        // si no no hace nada
        if (BotonEncender.getText().equals("APAGAR") && BotonAcelerar.getText().equals("ACELERAR")){
            estado.setText("FRENANDO");
        }
    }//GEN-LAST:event_BotonFrenarActionPerformed

    private void BotonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEncenderActionPerformed
        if (BotonEncender.getText().equals("ENCENDER")){
            BotonEncender.setForeground(Color.RED);
            BotonEncender.setText("APAGAR");
        }
        else{
            BotonEncender.setForeground(Color.GREEN);
            BotonEncender.setText("ENCENDER");
            estado.setText("APAGADO");
        }
    }//GEN-LAST:event_BotonEncenderActionPerformed

    private void BotonAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAcelerarActionPerformed
        // Acelerando solo si el motor está encendido y no se está frenando, si no no hace nada
        if (BotonEncender.getText().equals("APAGAR") && !estado.getText().equals("FRENANDO")){
            estado.setText("ACELERANDO");
            BotonAcelerar.setText("SOLTAR ACELERADOR");
            BotonAcelerar.setForeground(Color.RED);
        }
        
        BotonAcelerar.setText("ACELERAR");
        BotonAcelerar.setForeground(Color.BLACK);
    }//GEN-LAST:event_BotonAcelerarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonAcelerar;
    private javax.swing.JToggleButton BotonEncender;
    private javax.swing.JButton BotonFrenar;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
