/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package s4;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author jlgallego99
 */
public class PanelBotones extends javax.swing.JPanel implements Runnable{
    
    private EstadoMotor estadomotor = EstadoMotor.APAGADO;
    Cliente cliente;
    
    /**
     * Creates new form PanelBotones
     */
    public PanelBotones() {
        initComponents();
        BotonEncender.setForeground(Color.GREEN);
        BotonEncender.setText("ENCENDER");
        estado.setText("APAGADO");
        estado.setForeground(Color.RED);
    }
    
    public EstadoMotor getEstadoMotor(){
        return estadomotor;
    }

    public void setCliente(Cliente cliente) {
        this.cliente = cliente;
    }
    
    @Override
    public void run() {
        while (true){
            if(BotonEncender.isSelected()){
                BotonEncender.setForeground(Color.RED);
                BotonEncender.setText("APAGAR");
                estado.setText("ENCENDIDO");
                estado.setForeground(Color.GREEN);
                estadomotor = EstadoMotor.ENCENDIDO;
                if(BotonAcelerar.isSelected()){
                    estado.setText("ACELERANDO");
                    estado.setForeground(Color.GREEN);
                    estadomotor = EstadoMotor.ACELERANDO;
                    BotonFrenar.setSelected(false);
                }
                else if(BotonFrenar.isSelected()){
                    estado.setText("FRENANDO");
                    estado.setForeground(Color.RED);
                    estadomotor = EstadoMotor.FRENANDO;
                    BotonAcelerar.setSelected(false);
                }
            }
            else{
                BotonEncender.setForeground(Color.GREEN);
                BotonEncender.setText("ENCENDER");
                estado.setText("APAGADO");
                estado.setForeground(Color.RED);
                estadomotor = EstadoMotor.APAGADO;
                BotonAcelerar.setSelected(false);
                BotonFrenar.setSelected(false);
            }
            this.cliente.ejecutar(estadomotor);
            this.repaint();
            this.revalidate();
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(PanelBotones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BotonEncender = new javax.swing.JToggleButton();
        BotonAcelerar = new javax.swing.JToggleButton();
        BotonFrenar = new javax.swing.JToggleButton();
        estado = new javax.swing.JLabel();

        jLabel1.setText("Mandos");

        BotonEncender.setText("ENCENDER");
        BotonEncender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonEncenderActionPerformed(evt);
            }
        });

        BotonAcelerar.setText("ACELERAR");
        BotonAcelerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonAcelerarActionPerformed(evt);
            }
        });

        BotonFrenar.setText("FRENAR");
        BotonFrenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonFrenarActionPerformed(evt);
            }
        });

        estado.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BotonEncender)
                        .addGap(79, 79, 79)
                        .addComponent(BotonAcelerar))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(188, 188, 188)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(estado)
                            .addComponent(jLabel1))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 104, Short.MAX_VALUE)
                .addComponent(BotonFrenar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addComponent(estado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotonEncender)
                    .addComponent(BotonAcelerar)
                    .addComponent(BotonFrenar))
                .addGap(21, 21, 21))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotonEncenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonEncenderActionPerformed

    }//GEN-LAST:event_BotonEncenderActionPerformed

    private void BotonAcelerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonAcelerarActionPerformed

    }//GEN-LAST:event_BotonAcelerarActionPerformed

    private void BotonFrenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonFrenarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonFrenarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton BotonAcelerar;
    private javax.swing.JToggleButton BotonEncender;
    private javax.swing.JToggleButton BotonFrenar;
    private javax.swing.JLabel estado;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables

}
