/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package SCACV_Vista;

import SCACV_Controlador.*;
import java.text.DecimalFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;

/**
 *
 * @author jlgallego99
 */
public class Salpicadero extends javax.swing.JPanel implements Runnable {
    Controlador controlador;
    private static final DecimalFormat decimales = new DecimalFormat("#.###");
    
    public Salpicadero() {
        initComponents();
        
        // Títulos del panel de cada parte del salpicadero
        salpicadero.setBorder(BorderFactory.createTitledBorder("Salpicadero"));
        velocimetro.setBorder(BorderFactory.createTitledBorder("Velocímetro"));
        cuentakilometros.setBorder(BorderFactory.createTitledBorder("Cuentakilómetros"));
    }
    
    public void setControlador(Controlador controlador) {
        this.controlador = controlador;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        salpicadero = new javax.swing.JPanel();
        velocimetro = new javax.swing.JPanel();
        radial1 = new eu.hansolo.steelseries.gauges.Radial();
        radial2 = new eu.hansolo.steelseries.gauges.DigitalRadial();
        cuentakilometros = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cuentarrevoluciones = new javax.swing.JPanel();
        combustible = new eu.hansolo.steelseries.gauges.LinearBargraph();
        display1 = new eu.hansolo.steelseries.gauges.DisplaySingle();
        display2 = new eu.hansolo.steelseries.gauges.DisplaySingle();
        jLabel1 = new javax.swing.JLabel();

        radial1.setMaxValue(300.0);
        radial1.setTitle("Velocímetro");
        radial1.setUnitString("Km/h");

        radial2.setMaxValue(5000.0);

        javax.swing.GroupLayout velocimetroLayout = new javax.swing.GroupLayout(velocimetro);
        velocimetro.setLayout(velocimetroLayout);
        velocimetroLayout.setHorizontalGroup(
            velocimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(velocimetroLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(radial1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(radial2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );
        velocimetroLayout.setVerticalGroup(
            velocimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(velocimetroLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(velocimetroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radial1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(velocimetroLayout.createSequentialGroup()
                        .addComponent(radial2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jLabel2.setText("Reciente:");

        combustible.setMaxValue(500.0);
        combustible.setTitle("Combustible");

        javax.swing.GroupLayout cuentarrevolucionesLayout = new javax.swing.GroupLayout(cuentarrevoluciones);
        cuentarrevoluciones.setLayout(cuentarrevolucionesLayout);
        cuentarrevolucionesLayout.setHorizontalGroup(
            cuentarrevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuentarrevolucionesLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(combustible, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        cuentarrevolucionesLayout.setVerticalGroup(
            cuentarrevolucionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuentarrevolucionesLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(combustible, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setText("Total:");

        javax.swing.GroupLayout cuentakilometrosLayout = new javax.swing.GroupLayout(cuentakilometros);
        cuentakilometros.setLayout(cuentakilometrosLayout);
        cuentakilometrosLayout.setHorizontalGroup(
            cuentakilometrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuentakilometrosLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(display1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(display2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addComponent(cuentarrevoluciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        cuentakilometrosLayout.setVerticalGroup(
            cuentakilometrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(cuentakilometrosLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(cuentakilometrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(cuentakilometrosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(display1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(display2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cuentarrevoluciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout salpicaderoLayout = new javax.swing.GroupLayout(salpicadero);
        salpicadero.setLayout(salpicaderoLayout);
        salpicaderoLayout.setHorizontalGroup(
            salpicaderoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salpicaderoLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(velocimetro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(cuentakilometros, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        salpicaderoLayout.setVerticalGroup(
            salpicaderoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(salpicaderoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(velocimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cuentakilometros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(salpicadero, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(salpicadero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private eu.hansolo.steelseries.gauges.LinearBargraph combustible;
    private javax.swing.JPanel cuentakilometros;
    private javax.swing.JPanel cuentarrevoluciones;
    private eu.hansolo.steelseries.gauges.DisplaySingle display1;
    private eu.hansolo.steelseries.gauges.DisplaySingle display2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private eu.hansolo.steelseries.gauges.Radial radial1;
    private eu.hansolo.steelseries.gauges.DigitalRadial radial2;
    private javax.swing.JPanel salpicadero;
    private javax.swing.JPanel velocimetro;
    // End of variables declaration//GEN-END:variables

    @Override
    public void run() {
        while (true) {
            radial1.setValueAnimated(controlador.getVelocidad());
            radial2.setValueAnimated(controlador.getRPM());
            combustible.setValueAnimated(controlador.getCombustible());
            display1.setLcdValueAnimated(controlador.getDistanciaAcumulada());
            display2.setLcdValueAnimated(controlador.getDistanciaActual());
            
            
            this.repaint();
            this.revalidate();
            try {
                Thread.sleep(1000);
            } catch (InterruptedException ex) {
                Logger.getLogger(PanelBotones.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
